add: unit tests
reichlab/covid19-forecast-hub-validations pull request #32
Opened 2021-11-12 17:52 UTC by vidhi-mody

2021-11-19 14:24 UTC, Serena-Wang commented
All look good! Thanks, Vidhi!

Could you add a test case that a file path is not categorized to be any of those 4 PullRequestFileType?

2021-11-19 14:25 UTC, Serena-Wang requested changes
All look good! Thanks, Vidhi!

Could you add a test case that a file path is not categorized to be any of those 4 PullRequestFileType?

2021-11-20 00:24 UTC, vidhi-mody commented
> All look good! Thanks, Vidhi!
> 
> Could you add a test case that a file path is not categorized to be any of those 4 PullRequestFileType?

The code categories a PR as `OTHER_NONFS` if it doesn't belong to any of the other three PullRequestFileTypes. So a PR will always fall into one of the 4 PullRequestFileTypes.

2021-12-01 16:51 UTC, Serena-Wang requested changes
Thanks!

2021-12-01 16:51 UTC, Serena-Wang commented on tests/test_metadata_content.py
> +        self.assertIn("METADATA ERROR: Metadata YAML Fromat Error", errors[0])
small typo in error msg here and a couple of places below

2021-12-01 16:51 UTC, Serena-Wang commented on tests/test_metadata_content.py
> +    def test_invalid_metadata_file_format(self):
I think special characters and extra spaces are not checked in the current validation.

 If you add this feature to metadata.py , please also commit that file. And maybe we should have a more informative error msg for this case.

2021-12-10 21:50 UTC, merged