Config tests
reichlab/covid19-forecast-hub-validations pull request #51
Opened 2022-01-18 16:13 UTC by vidhi-mody

2022-01-19 16:40 UTC, Serena-Wang requested changes
Thanks! There are some places that need changes in the comments below. 

Also, we should add a case when a metadata file is located out of any model folder which is similar to the case you have at line 128 for forecast file.

2022-01-19 16:40 UTC, Serena-Wang commented on tests/test_file_location.py
> +    def valid_forecast_location(self, actual, forecast_file):
this test case is the same as valid_file_name below right?

2022-01-19 16:40 UTC, Serena-Wang commented on tests/test_file_location.py
> +    def invalid_file_name(self, actual, forecast_file):
This is the same as  invalid_metadata_file?

2022-01-19 17:01 UTC, vidhi-mody commented on tests/test_file_location.py
> +    def valid_forecast_location(self, actual, forecast_file):
Yes! Should I remove it since the input to both functions is a valid file?

2022-01-19 17:02 UTC, vidhi-mody commented on tests/test_file_location.py
> +    def invalid_file_name(self, actual, forecast_file):
Yes but the input passed to both functions is different. Since both txt/csv files are included in `OTHER_FS` output remains the same.

2022-01-19 17:04 UTC, vidhi-mody commented
I have added a case when a metadata file is located out of any model folder

2022-01-19 17:14 UTC, Serena-Wang commented on tests/test_file_location.py
> +    def invalid_file_name(self, actual, forecast_file):
I think we should delete duplicate test case functions and rename functions in ValidationFileLocationTest class to only include file type they are checking. We could add documentation around them to specify how it would check for forecast/metadata file location.

2022-01-27 13:54 UTC, Serena-Wang approved these changes

2022-01-27 13:55 UTC, merged