do not check model designation if metadata file is updated
reichlab/covid19-forecast-hub-validations pull request #70
Opened 2022-04-24 06:21 UTC by vidhi-mody

closes #69 

Link to test PRs:
Valid file: https://github.com/vidhi-mody/covid19-forecast-hub/pull/13
Invalid file: https://github.com/vidhi-mody/covid19-forecast-hub/pull/14

2022-04-27 22:21 UTC, Serena-Wang requested changes

2022-04-27 22:21 UTC, Serena-Wang commented on forecast_validation/validation_logic/metadata.py
> +        if team_models[metadata['team_name']]:
Could you add more documentation of what cases you are check here? And also modify error messages to be more descriptive?

2022-04-27 22:21 UTC, Serena-Wang commented on forecast_validation/validation_logic/metadata.py
> +            if metadata['model_name'] not in team_models[metadata['team_name']]:
For example, this is checking the case when an existing team add a new model with "primary" designation

2022-04-27 22:21 UTC, Serena-Wang commented on forecast_validation/validation_logic/metadata.py
> +            if metadata['model_name'] not in team_models[metadata['team_name']]:
For example, this is checking the case when an existing team add a new model with "primary" designation

2022-04-27 22:21 UTC, Serena-Wang commented on forecast_validation/validation_logic/metadata.py
> +                if model_designation[metadata['model_name']] == 'secondary':
I'm think we should keep a list of "primary" models for each team. Our current implicit assumption is that each team should have a primary model. In this case we are checking if an existing team changes designation from "secondary" to "primary" for an existing model. Before we throw an error, we should confirm that they do have another model with "primary" designation which causes this conflict.

2022-04-27 22:21 UTC, Serena-Wang commented on forecast_validation/validation_logic/metadata.py
> +                if model_designation[metadata['model_name']] == 'secondary':
I'm thinking if we should keep a list of "primary" models for each team. Our current implicit assumption is that each team should have a primary model. In this case we are checking if an existing team changes designation from "secondary" to "primary" for an existing model. Before we throw an error, we should confirm that they do have another model with "primary" designation which causes this conflict.

2022-04-27 22:21 UTC, Serena-Wang commented on forecast_validation/validation_logic/metadata.py
So if a new team submits a new "primary" model, it is dealt with the implicit "else" part of the if statement at line 79? Does the "else" part also takes care of the case when a team changes "primary" model designation to "secondary"? If so, could you document these in the code?

2022-04-27 22:21 UTC, Serena-Wang commented on forecast_validation/validation_logic/metadata.py
So if a new team submits a new "primary" model, it is dealt with the implicit "else" part of the if statement at line 79?

2022-06-24 21:13 UTC, elray1 commented
Two comments while I'm looking at this:

 1. Why are we using Zoltar to get information about metadata rather than just reading in the metadata files from the hub repository? Using Zoltar (a) seems like it introduces an extra dependency; not all hubs may have set up syncing to Zoltar, but we'd still want to be able to do this validation; (b) potentially introduces some race conditions, e.g. if multiple PRs updating model designations come in before updates are sent to Zoltar.

 2. I am wondering if some streamlined logic for this could work along these lines? This could use the existing [get_metadata_for_model](https://github.com/reichlab/covid19-forecast-hub-validations/blob/16482f327f4e313356682584e80486fb6b024b93/forecast_validation/utilities/github.py#L43) function (perhaps with modification to get metadata contents including updates from the PR?), and I think would mean we would not need to add extra data tracking structure like keeping a list of primary models.

    - for each team for which the current pull request updates at least one metadata file:
        - get the model designation for all of that team's models, according to the state of the hub repo that would be in effect if the PR were merged
        - if more than two of that team's models have primary status, throw an error

2022-07-06 18:28 UTC, elray1 commented
We took another route to closing this issue in PR #77

2022-07-06 18:28 UTC, closed without merging